'use strict';

/**
 * @ngdoc service
 * @name elicngApp.centurionranks
 * @description
 * # centurionranks
 * Factory in the elicngApp.
 */
angular.module('elicngApp')
  .factory('centurionranks', function () {

    return {
      getRanks: function () {
          return [
              "Baby",
              "Kid",
              "Kid",
              "Kid",
              "Kid",
              "Kid",
              "Kid",
              "Kid",
              "Kid",
              "Kid",
              "Teen",
              "Teen",
              "Teen",
              "Teen",
              "Teen",
              "Teen",
              "Teen",
              "Teen",
              "Teen",
              "Teen",
              "Peasant",
              "Peasant",
              "Peasant",
              "Peasant",
              "Peasant",
              "Peasant",
              "Peasant",
              "Peasant",
              "Peasant",
              "Peasant",
              "Citizen",
              "Citizen",
              "Citizen",
              "Citizen",
              "Citizen",
              "Citizen",
              "Citizen",
              "Citizen",
              "Citizen",
              "Citizen",
              "Free holder",
              "Free holder",
              "Free holder",
              "Free holder",
              "Free holder",
              "Free holder",
              "Free holder",
              "Free holder",
              "Free holder",
              "Free holder",
              "Velites",
              "Velites",
              "Velites",
              "Velites",
              "Velites",
              "Velites",
              "Velites",
              "Velites",
              "Velites",
              "Velites",
              "Legionaire",
              "Legionaire",
              "Legionaire",
              "Legionaire",
              "Legionaire",
              "Legionaire",
              "Legionaire",
              "Legionaire",
              "Legionaire",
              "Legionaire",
              "Cornicen",
              "Cornicen",
              "Cornicen",
              "Cornicen",
              "Cornicen",
              "Cornicen",
              "Cornicen",
              "Cornicen",
              "Cornicen",
              "Cornicen",
              "Tesserarius",
              "Tesserarius",
              "Tesserarius",
              "Tesserarius",
              "Tesserarius",
              "Tesserarius",
              "Tesserarius",
              "Tesserarius",
              "Tesserarius",
              "Tesserarius",
              "Optio",
              "Optio",
              "Optio",
              "Optio",
              "Optio",
              "Optio",
              "Optio",
              "Optio",
              "Optio",
              "Optio",
              "Centurion"];
      }
    };
  });
